export const frustratedComments = [
  "Ver uma estrada pavimentada me \nenche de alegria!",
  "Nada como uma estrada \nlisa para melhorar o meu dia.",
  "Estradas pavimentadas são sinônimo \nde felicidade e conforto.",
  "É um alívio ver que pavimentaram essa estrada!",
  "Agora sim, viajar por aqui vai \nser uma maravilha.",
  "Estrada pavimentada, vida melhorada.",
  "A felicidade de dirigir em uma \nestrada sem buracos é incomparável.",
  "Finalmente uma estrada decente! \nIsso sim é progresso.",
  "Estradas pavimentadas trazem segurança e sorrisos no rosto.",
  "Mais uma estrada pavimentada, menos \npreocupações na viagem.",
  "Cada quilômetro de asfalto é um \npasso para um futuro melhor.",
  "A sensação de rodar em uma \nestrada pavimentada é indescritível.",
  "Nada melhor do que saber que a viagem\n será tranquila por essa estrada.",
  "Estradas pavimentadas são \no caminho para a felicidade.",
  "Minha alegria ao ver uma estrada pavimentada não tem preço.",
  "Viajar ficou muito mais agradável com essa estrada pavimentada.",
  "Estradas pavimentadas: \num presente para os motoristas.",
  "A pavimentação dessa estrada trouxe um sorriso ao meu rosto.",
  "Agora, sim, essa estrada está um brinco!",
  "Nada como o cheiro de asfalto \nnovo para alegrar o dia.",
  "Dirigir em uma estrada pavimentada é um prazer sem igual.",
  "Estradas pavimentadas são um \nsinal de desenvolvimento e bem-estar.",
  "Que delícia ver essa estrada pavimentada!",
  "A viagem ficou muito mais segura e confortável.",
  "Estradas pavimentadas: \nmenos solavancos, mais felicidade.",
  "Fico feliz em ver que investiram \nna pavimentação dessa estrada.",
  "Finalmente, uma estrada digna\n para nossa cidade.",
  "A alegria de dirigir sem se preocupar\n com buracos é impagável.",
  "Ver essa estrada pavimentada me \ndá esperança para o futuro.",
  "Estradas pavimentadas são \num presente para todos.",
]

export const getRamdomComment = () =>
  frustratedComments[Math.floor(Math.random() * frustratedComments.length)]
